# Generated by Django 4.0.4 on 2022-05-14 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothes', '0003_remove_product_product_type_delete_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_shirt', models.BooleanField(default=False)),
                ('shirt', models.BooleanField(default=False)),
                ('jacket', models.BooleanField(default=False)),
                ('suit', models.BooleanField(default=False)),
                ('blouse', models.BooleanField(default=False)),
                ('dress', models.BooleanField(default=False)),
                ('pants', models.BooleanField(default=False)),
                ('short', models.BooleanField(default=False)),
                ('skirt', models.BooleanField(default=False)),
                ('crop_top', models.BooleanField(default=False)),
                ('hoodie', models.BooleanField(default=False)),
                ('jeans', models.BooleanField(default=False)),
                ('polo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, unique=True)),
                ('passworld', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(max_length=200)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.product_type')),
            ],
        ),
    ]
