# Generated by Django 4.0.4 on 2022-05-14 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Product_type',
        ),
    ]
