# Generated by Django 4.0.4 on 2022-05-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_alter_product_image_alter_product_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.ManyToManyField(to='clothes.product_size'),
        ),
    ]
