# Generated by Django 4.0.4 on 2022-05-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0008_product_size_product_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passworld',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
