# Generated by Django 4.0.4 on 2022-05-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0009_rename_passworld_user_password_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_size',
            new_name='ProductSize',
        ),
        migrations.RenameModel(
            old_name='Product_type',
            new_name='ProductType',
        ),
    ]
