# Generated by Django 4.0.4 on 2022-05-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0010_rename_product_size_productsize_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSize',
            new_name='Product_size',
        ),
        migrations.RenameModel(
            old_name='ProductType',
            new_name='Product_type',
        ),
    ]
