# Generated by Django 4.0.4 on 2022-05-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0013_product_adapter_alter_user_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_type',
            name='product_type',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
