# Generated by Django 4.0.4 on 2022-05-16 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0014_alter_product_type_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_product', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.product')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.product_size')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Product_adapter',
        ),
        migrations.AddField(
            model_name='cart_item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.user'),
        ),
    ]
