# Generated by Django 4.0.4 on 2022-05-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0015_cart_item_remove_user_cart_delete_product_adapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='sum_price',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
