# Generated by Django 4.0.4 on 2022-05-17 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0017_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_product', models.IntegerField()),
                ('sum_price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='number_product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_size',
        ),
        migrations.DeleteModel(
            name='Cart_item',
        ),
        migrations.AddField(
            model_name='product_item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.order'),
        ),
        migrations.AddField(
            model_name='product_item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.product'),
        ),
        migrations.AddField(
            model_name='product_item',
            name='product_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.product_size'),
        ),
        migrations.AddField(
            model_name='product_item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.user'),
        ),
    ]
