# Generated by Django 4.0.4 on 2022-05-17 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0019_rename_phone_order_phone_receive_order_user_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_product', models.IntegerField()),
                ('sum_price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.product')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.product_size')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_product', models.IntegerField()),
                ('sum_price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.product')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.product_size')),
            ],
        ),
        migrations.DeleteModel(
            name='Product_item',
        ),
    ]
