# Generated by Django 4.0.4 on 2022-05-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0021_rename_froduct_for_male_product_product_for_male'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_for_male',
        ),
    ]
